### ISSUE TITLE
Option to hide room numbers

### ISSUE THREAD

**Issue by dhimelick** [dcbradley/building-access#1]
The recent update to allow hiding names on the schedule is great. However, I've also received a request to be able to hide room numbers on the schedule, as even that amount of information could be identifying if it's an office number.

If I have time, I'll look at creating a pull request for such a feature, but I wanted to open this issue in case I can't.

**Comment by dcbradley** [comment]
Hiding room numbers in the occupancy list would be a simple matter in usage_info.php.  We could add a configuration variable to toggle the behavior.  However, it raises a question.  If somebody tries to schedule some time in a room that is occupied, and either "NormCap" or "MaxCap" are exceeded for that room, what information should be revealed to the registrant?  Currently, it tells them about the level of occupancy.  In addition, the people's names are either revealed or not, depending on privacy settings.

**Comment by dhimelick** [comment]
That's a good question, and one that I didn't really think about because most of the rooms we're dealing with are individual offices which typically won't get multiple requests at once. I guess that, if a room hiding option existed, it would have to suppress any occupancy cap errors so as not to reveal if someone is occupying that room. It would then go to the approver to figure out how to respond to that request.

Perhaps there could be an optional column in a roomcaps CSV to indicate "individual office" as well as configuration options similar to the name hiding options? If a room is marked as an individual office AND the proper configurations are set, then the room number would be hidden in the schedule as well (or there would be a checkbox to allow the person to choose to do this). I'm not sure how much more complexity that would add. It certainly would add some extra setup work to use the feature.

I did also suggest to the person who asked about this that they could put anything they want as the room as long as the approver understands the request. Perhaps that's good enough? I'm not sure, as it still may highlight their entry if it looks different from others. I can check.

**Comment by dcbradley** [comment]
Sorry for the delay.  No time to think these days.  To make progress, would it be useful to you to just have a configuration variable that turns off the individual occupancy listing for non-admins?  They could still see the building occupancy totals, but nothing else.  Or if the building occupancy totals aren't all that useful, we could just turn off that whole section of the form.

**Comment by dhimelick** [comment]
A configuration variable to turn off individual occupancy listing for non-admins would be great as long as requesters can still view their own requests to edit them. Even though building occupancy totals aren't that useful for us, I think we'd still like the keep that section of the form, and it probably makes sense for editing your own requests anyway.

No problem on the delay. We're all quite busy at the start of a normal semester, and this isn't normal. I appreciate the time you've put into accommodating outside requests!

**Comment by dcbradley** [comment]
Sounds good then.  There is now a configuration variable SHOW_ANONYMOUS_ROOM_OCCUPANCY, which can be set to false to hide anonymous entries from the occupancy list. 7962de5fac00ddbb2f975a8e7c3c368073eb04f6

You can also use the new 'Act As' feature to see the form as a non-admin would see it.
