### ISSUE TITLE
Mass approval

### ISSUE THREAD

**Issue by dhimelick** [dcbradley/building-access#2]
We've had a few requests from our approvers to be able to approve requests en masse. I think they've been getting quite a few repeating requests for the semester, which generates a ton of individual requests for approval on the Pending tab. In its simplest form, I think this could be a "check all" checkbox in the Aprv header.

**Comment by dcbradley** [comment]
Good idea.  Checkboxes have been added for checking all the boxes in each column.  ef33e6459911ef68ad1b181ff26ea36934fa5214
