### ISSUE TITLE
call_user_func and php 7.2 warnings

### ISSUE THREAD

**Issue by sknolin** [dcbradley/building-access#3]
I am not a php programmer, so may be wrong in my guess, but here's what I've seen.

call_user_func does not pass parameters by reference. It still works because? php?

But with newer versions, it also prints out a warning:

Warning: Parameter 1 to saveRequest() expected to be a reference, value given in /var/www/html/building-access/index.php on line 53

I just changed the function and call to use values, and it seems to work.

index.php

```
<         call_user_func($handler->handler_fn,array($show));

---
>         call_user_func($handler->handler_fn,array(&$show));
```
registration.php

```
< function saveRequest($show) {
---
> function saveRequest(&$show) {
---
< function requestApproval($show) {
---
> function requestApproval(&$show) {
```

**Comment by dcbradley** [comment]
Interesting.  What version of PHP?

Anyway, there's no need for this app to depend on this esoteric feature of PHP.  I pushed a patch to the master branch to get rid of it (e5d34cfbe46c9118844cc3c4305a9247c1573c26).  As you found, there was nothing very important that depended on modifying the argument anyway.

**Comment by dcbradley** [comment]
I see that you already specified that the problem appeared in PHP 7.2.  Got it.
