### ISSUE TITLE
NORMCAP and DESCRIPTION are required fields in roomcaps/deptname.csv

### ISSUE THREAD

**Issue by ewdieckman** [dcbradley/building-access#4]
When calling `getRoomCap` in `common.php`, it will produce an error if the NORMCAP or DESCRIPTION fields are omittted in the roomcaps/deptname.csv.

> **Notice:** Undefined index: NORMCAP in **{location}/common.php** on line **401**.
> **Notice:** Undefined index: DESCRIPTION in **{location}/common.php** on line **403**.

An option that could work (or just update documentation to say that NORMCAP and DESCRIPTION are required)

```php
# common.php:392 - check for existence of array keys
function getRoomCap($room,$building) {
  $roomcaps = getRoomCaps($building);

  $normcap = 1;
  $maxcap = 1;
  $description = "";

  if( $roomcaps && array_key_exists($room,$roomcaps) ) {
    $roomcap = $roomcaps[$room];
    if( array_key_exists($roomcap,NORMCAP) ) $maxcap = (int)$roomcap['NORMCAP'];
    $maxcap = (int)$roomcap['MAXCAP'];
    if( array_key_exists($roomcap,DESCRIPTION) ) $description = $roomcap['DESCRIPTION'];
  }
```

**Comment by dcbradley** [comment]
Oops.  Good point.  Patched!  ec34a9753c76c405156c787ec8da37e698044231
